// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/truly-indian/reverseImageSearch/internal/config"
	"github.com/truly-indian/reverseImageSearch/internal/crawler"
	"github.com/truly-indian/reverseImageSearch/internal/groq"
	"github.com/truly-indian/reverseImageSearch/internal/logger"
	"github.com/truly-indian/reverseImageSearch/internal/openai"
	"github.com/truly-indian/reverseImageSearch/internal/reverseimagegenerator"
	"github.com/truly-indian/reverseImageSearch/internal/server"
	"github.com/truly-indian/reverseImageSearch/internal/serviceclients"
	"github.com/truly-indian/reverseImageSearch/internal/utils"
)

// Injectors from di.go:

func InitDependencies() (ServerDependencies, error) {
	configConfig := config.GetConfig()
	loggerLogger := logger.NewLogger()
	serverServer := server.NewServer(configConfig, loggerLogger)
	client := server.NewHTTPClient()
	httpClient := utils.GetHTTPClient()
	serpAPIClient := serviceclients.NewSerpAPIClient(client, configConfig, httpClient, loggerLogger)
	openaiClient := openai.NewOpenAIClient(configConfig, loggerLogger)
	groqClient := groq.NewGroq(configConfig, loggerLogger)
	llmCrawler := crawler.NewLLMCrawler(openaiClient, configConfig, loggerLogger, groqClient)
	crawlerCrawler := crawler.NewCrawler(configConfig, loggerLogger, llmCrawler)
	service := reverseimagegenerator.NewService(configConfig, serpAPIClient, crawlerCrawler, loggerLogger)
	handler := reverseimagegenerator.NewHandler(configConfig, service, loggerLogger)
	handlers := server.Handlers{
		ReverseImageGenerator: handler,
	}
	serverDependencies := ServerDependencies{
		config:   configConfig,
		server:   serverServer,
		handlers: handlers,
	}
	return serverDependencies, nil
}

// di.go:

type ServerDependencies struct {
	config   *config.Config
	server   *server.Server
	handlers server.Handlers
}
